// Generated by tools/bump.mjs — the app version lives in
// velta-app/src-tauri/Cargo.toml; don't edit this file by hand.
// Committed (not gitignored) so mock/PWA mode works on a fresh clone.
export const APP_VERSION = "1.4.59";
