#!/usr/bin/env node
// bump.mjs <version> — the single version-bump command (AGENTS.md "Version bumps").
// Truth: velta-app/src-tauri/Cargo.toml [package].version. This rewrites it,
// syncs the velta-app entry in Cargo.lock, regenerates app/js/version.gen.js
// (PWA/mock fallback imported by ui.js), and mirrors it into tauri.conf.json —
// the tauri-cli Android build reads ONLY the conf field for
// tauri.android.versionName/Code (no Cargo fallback), so without it the APK
// ships as versionCode 1 / versionName "1.0" (what happened in v1.4.58).
// Idempotent: re-running with the current version is a no-op.
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath, pathToFileURL } from "node:url";

export function bumpVersion(v, readFile, writeFile) {
  if (!/^v?\d+\.\d+\.\d+(-[\w.]+)?$/.test(v)) throw new Error(`not a semver: ${v}`);
  v = v.replace(/^v/, "");

  const cargo = readFile("velta-app/src-tauri/Cargo.toml");
  // [package] is the first section, so the first `version = ` is the package's.
  const m = cargo.match(/^version = "([^"]*)"/m);
  if (!m) throw new Error("version key not found in Cargo.toml [package]");
  writeFile("velta-app/src-tauri/Cargo.toml", cargo.replace(/^version = "[^"]*"/m, `version = "${v}"`));

  const lockPath = "velta-app/src-tauri/Cargo.lock";
  const lock = readFile(lockPath);
  if (!/\[\[package\]\]\r?\nname = "velta-app"\r?\nversion = "/.test(lock)) {
    throw new Error("velta-app entry not found in Cargo.lock");
  }
  writeFile(lockPath, lock.replace(
    /(\[\[package\]\]\r?\nname = "velta-app"\r?\nversion = )"[^"]*"/,
    `$1"${v}"`,
  ));

  const confPath = "velta-app/src-tauri/tauri.conf.json";
  const conf = readFile(confPath);
  if (/"version":\s*"[^"]*"/.test(conf)) {
    writeFile(confPath, conf.replace(/"version":\s*"[^"]*"/, `"version": "${v}"`));
  } else {
    const eol = conf.includes("\r\n") ? "\r\n" : "\n";
    writeFile(confPath, conf.replace(
      /(\r?\n(\s*)"identifier":\s*"[^"]*"),/,
      `$1,${eol}$2"version": "${v}",`,
    ));
  }

  writeFile(
    "app/js/version.gen.js",
    `// Generated by tools/bump.mjs — the app version lives in\n` +
      `// velta-app/src-tauri/Cargo.toml; don't edit this file by hand.\n` +
      `// Committed (not gitignored) so mock/PWA mode works on a fresh clone.\n` +
      `export const APP_VERSION = "${v}";\n`,
  );
  return { from: m[1], to: v };
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  try {
    const root = fileURLToPath(new URL("..", import.meta.url));
    const { from, to } = bumpVersion(
      process.argv[2],
      (p) => readFileSync(root + p, "utf8"),
      (p, c) => writeFileSync(root + p, c),
    );
    console.log(`bumped ${from} -> ${to} (Cargo.toml, Cargo.lock, tauri.conf.json, app/js/version.gen.js)`);
    console.log(`next: commit, tag v${to}, push (release.yml reads Cargo.toml)`);
  } catch (e) {
    console.error("bump failed:", e.message);
    process.exit(1);
  }
}
